name: "Upload data to biglocalnews.org"
author: 'Big Local News'
description: "Automatically archive your comma-delimited files with Big Local News"

branding:
  icon: 'upload-cloud'
  color: 'red'

inputs:
  api-key:
    description: |-
      Your biglocalnews.org API token.
    required: true
  project-id:
    description: |-
      The identifier of the biglocalnews.org project where the files will be uploaded.
    required: true
  path:
    description: |-
      The file or folder path inside the action's filesystem to upload.
    required: true

runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version:  3.9

    - id: install-deps
      name: Install Python dependencies
      run: pip install bln
      shell: bash

    - id: upload-files
      name: Upload files
      run: python ${{ github.action_path }}/upload.py
      shell: bash
      env:
          api-key: ${{ inputs.api-key }}
          project-id: ${{ inputs.project-id }}
          path: ${{ inputs.path }}
